export const BOOK_GENRES = [
    { value: "action", label: "Action" },
    { value: "adventure", label: "Adventure" },
    { value: "anthology", label: "Anthology" },
    { value: "arts-culture", label: "Arts & Culture" },
    { value: "autobiography", label: "Autobiography" },
    { value: "biography", label: "Biography" },
    { value: "business-economics", label: "Business & Economics" },
    { value: "childrens-fiction", label: "Children's Fiction" },
    { value: "contemporary-fiction", label: "Contemporary Fiction" },
    { value: "cooking-food", label: "Cooking & Food" },
    { value: "drama-plays", label: "Drama & Plays" },
    { value: "dystopian", label: "Dystopian" },
    { value: "education", label: "Education" },
    { value: "essays", label: "Essays" },
    { value: "fantasy", label: "Fantasy" },
    { value: "graphic-novels-comics", label: "Graphic Novels & Comics" },
    { value: "health-fitness", label: "Health & Fitness" },
    { value: "historical-fiction", label: "Historical Fiction" },
    { value: "history", label: "History" },
    { value: "horror", label: "Horror" },
    { value: "literary-fiction", label: "Literary Fiction" },
    { value: "memoir", label: "Memoir" },
    { value: "mystery", label: "Mystery" },
    { value: "paranormal", label: "Paranormal" },
    { value: "philosophy", label: "Philosophy" },
    { value: "poetry", label: "Poetry" },
    { value: "politics", label: "Politics" },
    { value: "psychology", label: "Psychology" },
    { value: "reference", label: "Reference" },
    { value: "religion-spirituality", label: "Religion & Spirituality" },
    { value: "romance", label: "Romance" },
    { value: "science", label: "Science" },
    { value: "science-fiction", label: "Science Fiction" },
    { value: "self-help", label: "Self-Help" },
    { value: "short-stories", label: "Short Stories" },
    { value: "technology", label: "Technology" },
    { value: "thriller", label: "Thriller" },
    { value: "true-crime", label: "True Crime" },
    { value: "travel", label: "Travel" },
    { value: "young-adult", label: "Young Adult (YA)" }
];